### ISSUE TITLE
Rounded corner mask incorrectly applied and crops full size images

### ISSUE THREAD

**Issue by TanByv** [refact0r/midnight-discord#15]
Top part of full size images gets cropped off, rounded corner is only applied to the top of the image (I don't know if it should be applied at all while viewing full size images). See picture for example, original image in the background where the missing top part is visible.

midnight.theme.css - commit f4022d0

![amogus](https://user-images.githubusercontent.com/43620837/228641075-1a9c02af-e3c3-484b-886d-b23da37e7368.PNG)

**Comment by TanByv** [comment]
```css
.root-1CAIjD /* create a server */ {
    border-radius: var(--roundness) !important;
    overflow: hidden;
}
```

Removing this part fixes the issue but introduces elements missing rounding elsewhere
