### ISSUE TITLE
[Bug] [Graphic] Incorrect rounding of buttons in the call menu

### ISSUE THREAD

**Issue by GLWine** [refact0r/midnight-discord#187]
## The icons in the call menu are rounded incorrectly:
The microphone and webcam buttons are circular, while the drop-down menu button is a half-squircle, creating a visually inconsistent and unaesthetic result.
![Image](https://github.com/user-attachments/assets/88209490-5098-45a6-be07-de45e4e9cf66) ![Image](https://github.com/user-attachments/assets/afb2c3c9-afc3-4f54-a4a5-9eb883072190)
![Image](https://github.com/user-attachments/assets/6f5d3cd8-700e-484b-9fd0-4d34ba302a34)

## This is a possible solution to the problem:
In my solution, all the keys are converted to squircles to ensure aesthetic consistency. Additionally, the dropdown menu key is slightly extended in height to align with the others.
![Image](https://github.com/user-attachments/assets/74d78ef8-3756-4480-9d0b-84794977846d) ![Image](https://github.com/user-attachments/assets/13ae7f06-6330-487f-bee4-474bd4bc1c8c)
![Image](https://github.com/user-attachments/assets/ee5c800e-5c3e-446a-b359-0704878e79a2)

```css
button.centerButton_f1ceac /* fix vc buttons */ {
    border-radius: 12px;
}
button.fullRegionButton_f1ceac /* fix vc button again */ {
	border-radius: 12px;
}

/* fix Mic/WebCam buttons */
.contextMenuNubExperiment_f1ceac.colorable_f1ceac.attachedCaret_f1ceac.experimentDark_f1ceac[role="button"][tabindex="0"] {
	border-top-left-radius: 0; 
    border-bottom-left-radius: 0;
    border-top-right-radius: 12px;
    border-bottom-right-radius: 12px;
	height: 24px;
}
/* fix Mic/WebCam option buttons */
button.staticButton_f1ceac.centerButton_f1ceac.colorable_f1ceac.experimentButton_f1ceac.colorable_f1ceac.experimentDark_f1ceac.attachedButton_f1ceac.button__201d5.lookBlank__201d5.colorBrand__201d5[type="button"] {
    border-top-left-radius: 12px; 
    border-bottom-left-radius: 12px;
    border-top-right-radius: 0;
    border-bottom-right-radius: 0;
}
```
