### ISSUE TITLE
User bar size bug when used in combination with BetterFolders plugin

### ISSUE THREAD

**Issue by MoonieGZ** [refact0r/midnight-discord#230]
Hi there, not sure if it's a theme problem or a plugin problem but when using midnight theme with BetterFolders enabled, this comically large user bar happens.

![Image](https://github.com/user-attachments/assets/86a0c2d7-102d-4d11-9df3-0f64233a052d)

**Comment by sadan4** [comment]
It's an issue with midnight as better folders was fixed to fix with visual refresh recently

in the meantime, I've been using this, which isn't perfect but does work

```css
.visual-refresh .vc-betterFolders-sidebar-grid {
    grid-template-columns: [start] min-content [guildsEnd] min-content [sidebarEnd] min-content [channelsEnd] 1fr [end];
    grid-template-areas:
        'titleBar titleBar titleBar titleBar'
        'guildsList betterFoldersSidebar notice notice'
        'guildsList betterFoldersSidebar channelsList page'
        'userPanel userPanel userPanel page';
}
```

**Comment by H4TK1D** [comment]
Better folders doesn't patch correctly or resize right. Currently there is a tempfix but it does not work with small user panel:

```css
.visual-refresh {
    .base_c48ade {
        grid-template-areas:
            'titleBar titleBar titleBar titleBar'
            'guildsList betterFoldersSidebar notice notice'
            'guildsList betterFoldersSidebar channelsList page'
            'userPanel userPanel userPanel page';
    }
    .vc-betterFolders-sidebar-grid {
        grid-template-columns: [start] min-content [guildsEnd] min-content [sidebarEnd] min-content [channelsEnd] 1fr [end];
    }
    .sidebarList_c48ade {
        width: calc(var(--custom-guild-sidebar-width) - var(--custom-guild-list-width) - var(--gap));
    }

    .panels_c48ade {
        max-width: calc(var(--custom-guild-sidebar-width) + var(--gap) + 4px + var(--gap) + 66px);
    }
}
```

**Comment by sadan4** [comment]
@H4TK1D As the person who fixed better folders, how is it done incorrectly? If there's a better way to do it that doesn't interfere with themes as much, I'd love to know.

**Comment by H4TK1D** [comment]
Basically the reason why it acts the way it does is because with midnight is because midnight overrides betterfolders grid-area css, kicking it out of the grid template, and making everything weird, so it reinserts it into the grid and makes sure the user panel can scale to the new size. It would likely be better if they made the plugin either class specify the sidebar or use !important to make sure that their css doesn't get overwritten, but that would also break themes

**Comment by H4TK1D** [comment]
Basically any theme that does not touch the grid area should still work in the current state and those who do are likely broken

**Comment by MoonieGZ** [comment]
Thank you both!

**Comment by clari7744** [comment]
I was just coming here to say something about this bug, because my whole left sidebar disappears when I use quick switcher to navigate to a server, but this actually fixes all of my issues (the server list was on the left of the folder list for some reason before, and now this bug). [H4TK1D](https://github.com/H4TK1D)'s fix works for me; not sure what you mean about "small user panel" though?

**Comment by LarveyOfficial** [comment]
@H4TK1D's fix does seem to work, but it causes a large gap whenever there are no folders open between the server list and the rest of the application. I haven't been able to find a fix for this just yet.

**Comment by Ronrii** [comment]
@LarveyOfficial It's not an ideal option, but I think it works as a temporary solution
```
.visual-refresh {
    .vc-betterFolders-sidebar-grid {
        grid-template-columns: [start] min-content [guildsEnd] min-content [sidebarEnd] min-content [channelsEnd] 1fr [end];
        grid-template-areas:
            'titleBar titleBar titleBar titleBar'
            'guildsList betterFoldersSidebar notice notice'
            'guildsList betterFoldersSidebar channelsList page'
            'userPanel userPanel userPanel page';
		column-gap: 6px;
    }
    .sidebarList_c48ade {
        width: calc(var(--custom-guild-sidebar-width) - var(--custom-guild-list-width) - var(--gap));
    }

    .panels_c48ade {
        max-width: calc(var(--custom-guild-sidebar-width) + var(--gap) + 4px + var(--gap) + 66px);
    }
}
```

**Comment by refact0r** [comment]
whats the ideal option

**Comment by H4TK1D** [comment]
> [@LarveyOfficial](https://github.com/LarveyOfficial) It's not an ideal option, but I think it works as a temporary solution
> 
> ```
> .visual-refresh {
>     .vc-betterFolders-sidebar-grid {
>         grid-template-columns: [start] min-content [guildsEnd] min-content [sidebarEnd] min-content [channelsEnd] 1fr [end];
>         grid-template-areas:
>             'titleBar titleBar titleBar titleBar'
>             'guildsList betterFoldersSidebar notice notice'
>             'guildsList betterFoldersSidebar channelsList page'
>             'userPanel userPanel userPanel page';
> 		column-gap: 6px;
>     }
>     .sidebarList_c48ade {
>         width: calc(var(--custom-guild-sidebar-width) - var(--custom-guild-list-width) - var(--gap));
>     }
> 
>     .panels_c48ade {
>         max-width: calc(var(--custom-guild-sidebar-width) + var(--gap) + 4px + var(--gap) + 66px);
>     }
> }
> ```
This resizes the column size so that the gap between the server list and the sidebar is smaller but also changes the gap between the main chat and the channel list, effectively not changing anything but making the gap smaller. There will still be a bigger gap while the sidebar isn't open

**Comment by H4TK1D** [comment]
```css
.visual-refresh {
    .vc-betterFolders-sidebar-grid {
        grid-template-columns: [start] min-content [guildsEnd] min-content [sidebarEnd] min-content [channelsEnd] 1fr [end];
        grid-template-areas:
            'titleBar titleBar titleBar titleBar'
            'guildsList betterFoldersSidebar notice notice'
            'guildsList betterFoldersSidebar channelsList page'
            'userPanel userPanel userPanel page';
    }
    .sidebarList_c48ade {
        width: calc(var(--custom-guild-sidebar-width) - var(--custom-guild-list-width) - var(--gap));
    }
    .sidebar_c48ade:not(:has(:nth-child(2) > [aria-label='Servers sidebar'])) {
        column-gap: 0;
    }
    .panels_c48ade {
        max-width: calc(var(--custom-guild-sidebar-width) + var(--gap) + 4px + var(--gap) + 66px);
    }
}
```

Okay do note that this is shady as hell but it does remove the unintentional gap created when the server folder list isn't opened (but because the second sidebar has no identifier whatsoever I'm basically forced to use the worst selector ever and hope it just is at the right place)
