### ISSUE TITLE
Status icon colors are set to discord default

### ISSUE THREAD

**Issue by enderprism** [refact0r/midnight-discord#234]
i noticed the status icons' colors were using Discord's default colors instead of catppuccin mocha's
i'm too lazy to open a PR but i wrote a quick fix for it.
```css
[fill="#40a258"] {
  fill: var(--online) !important;
}
[style*="background-color: rgb(64, 162, 88);"] {
  background-color: var(--online) !important;
}

[fill="#d83a41"] {
  fill: var(--dnd) !important;
}
[style*="background-color: rgb(216, 58, 65);"] {
  background-color: var(--dnd) !important;
}

[fill="#cc954c"] {
  fill: var(--idle) !important;
}
[style*="background-color: rgb(204, 149, 76);"] {
  background-color: var(--idle) !important;
}

[fill="#82838b"] {
  fill: var(--offline) !important;
}
[style*="background-color: rgb(130, 131, 139);"] {
  background-color: var(--offline) !important;
}
```

**Comment by enderprism** [comment]
these icons set their color differently. i updated the fix accordingly

**Comment by Savitar03** [comment]
Good job man, thanks for sharing. Idk why discord is not using the already defined mask/variable color

**Comment by enderprism** [comment]
discord changed every status color slightly so the patch broke.
here's the updated version:
```css
[fill="#43a25a"] {
  fill: var(--online) !important;
}

[style*="background-color: rgb(67, 162, 90);"] {
  background-color: var(--online) !important;
}

[fill="#d83a42"] {
  fill: var(--dnd) !important;
}

[style*="background-color: rgb(216, 58, 66);"] {
  background-color: var(--dnd) !important;
}

[fill="#ca9654"] {
  fill: var(--idle) !important;
}

[style*="background-color: rgb(202, 150, 84);"] {
  background-color: var(--idle) !important;
}

[fill="#82838b"] {
  fill: var(--offline) !important;
}

[style*="background-color: rgb(130, 131, 139);"] {
  background-color: var(--offline) !important;
}
```
