### ISSUE TITLE
Transparency and blur on context menus, various pop-ups, overlays, etc

### ISSUE THREAD

**Issue by iGerman00** [refact0r/midnight-discord#267]
Currently, a lot of the UI with floating things isn't blurred behind. While some people might like it, I find it extremely difficult to read. 
When I initially configured the theme, I thought that the following would affect all floating things let me have them blurry, but apparently not:
```css
    --panel-blur: on; /* off: no changes, on: blur the background of panels */
    --blur-amount: 12px; /* amount of blur */
    --bg-floating: var(--bg-3); /* set this to a more opaque color if floating panels look too transparent. only applies if panel blur is on  */
```
Additionally, it makes the panels not transparent anymore, so I've not included it at all. It doesn't have any effect on the floating things in the example below.

My current CSS overrides are:
```css
body {
    --top-bar-button-position: off;
    --top-bar-title-position: left;
    --top-bar-height: 36px;
    --custom-dms-icon: hide;
    font-weight: 500;

    --custom-window-controls: off;
    --subtle-top-bar-title: on;

    --transparency-tweaks: on;
    --bg-1: rgba(73, 77, 100, 0.5); /* dark buttons when clicked */
    --bg-2: rgba(54, 58, 79, 0.8); /* dark buttons */
    --bg-3: rgba(30, 32, 48, 0.8); /* spacing, secondary elements */
    --bg-4: rgba(36, 39, 58, 0.0); /* main background color */

    --custom-chatbar: separated;
    --chatbar-height: 56px;

    --small-user-panel: on;
}
```

My proposition is for these floating elements to have their own options to configure, because panel blur and such corresponds to panels and it might be difficult to have both transparent panels and blurred menus.

<sup>re: https://discord.com/channels/1169089289552924712/1169089290014314558/1365823355403370496</sup>

---

See examples:
![Image](https://github.com/user-attachments/assets/84e37c3d-43c1-4b4d-950c-e859dc1c8fd3)
![Image](https://github.com/user-attachments/assets/ad63bbd6-cf8c-43ee-8ae6-ff5c88c57a89)
![Image](https://github.com/user-attachments/assets/4c41479d-a513-4ebe-9f6e-9efb7b73c199)
![Image](https://github.com/user-attachments/assets/bee785aa-c913-4269-9c35-1ddc82c68472)
![Image](https://github.com/user-attachments/assets/29af67f6-5104-45b0-ae35-20c1c58e84c7)

And most egregiously, when the internet goes down:
![Image](https://github.com/user-attachments/assets/a4a4a70e-0e13-4ab5-8fb4-8684ae64f6d3)
