### ISSUE TITLE
BetterSpotifyPlayer Slight Incompatiblity

### ISSUE THREAD

**Issue by barraIhsan** [refact0r/midnight-discord#96]
[Raw CSS Import](https://raw.githubusercontent.com/Panniku/vc-snippets/main/BetterSpotifyPlayer.css)

So the spotify player is not the right color
![image](https://github.com/refact0r/midnight-discord/assets/57800056/155f2ad0-7260-4c1a-ad0b-49b5e79f0c85)

my dirty / temporary hack is to put
```css
/* Makes the spotify custom player the right bg color */
#app-mount .panels__58331 {
    background-color: var(--bg-4) !important;
}
```
and it also work when the user doesn't use the BetterSpotifyPlayer.

So is there a better way for this to be implemented?
